### ISSUE TITLE
Conform iCatcher output to Psych-DS standard

### ISSUE THREAD

**Issue by mekline** [icatcherplus/icatcher_plus#27]
The Psych-DS data standard is an in-process specification that's designed to be [BIDS](https://bids.neuroimaging.io/) for tabular behavioral datasets. (Funded to build the validator starting 1-2 months from now)

[Website](https://psych-ds.github.io/)
[Specification draft](https://docs.google.com/document/d/1u8o5jnWk0Iqp_J06PTu5NjBfVsdoPbBhstht6W0fFp0/edit)

In the long term, it would be amazing to have iCatcher+ officially support this output format.  In the short term, the following choices about folder structure & file naming would support eventual standard adoption with the workflow discussed today.  

It's also totally fine if all/some of this isn't achievable right now - happy to discuss!

The major key points for the standard are:

- all data (and only data) wind up inside of a subfolder named 'data'
- CSV filenames have the structure key-value_key-value_key-value_data.csv (where the alphanumeric string up to the first '-' is considered the key.)

So for this tool, I'm proposing that you instruct the user to put their video files inside of a data folder, and they'll be getting a parallel folder called 'icatcher' containing all annotations.   I used 'label-raw' and 'label-corrections' as the key-value pattern below, but this could be anything else with the same structure. 

Bonus notes: The format of videos downloaded from Lookit is currently the following: 

`videoStream_{study_uuid}_{order-frame_name}_{response_uuid}_{timestamp}_{randomDigits}.mp4`

In the future (probably farther off), we will be having Lookit export videos with names like the following: 

`videoStream_study-{study-uuid}_frame-{order-frame-name}_response-{response-uuid}_timestamp-{timestamp}_hash-{randomDigits}.mp4`

If possible, it would be great to have iCatcher output to conform to the Psych-DS filenaming convention when the video filename follows the current structure - I show both the structure & an example below.  

If not, treating the current Lookit video names the same as any other arbitrary filename would also be a fine intermediate step, e.g. `label-corrections_video-videoStream_{study-uuid}_{order-frame-name}_{response-uuid}_{timestamp}_{randomDigits}_data.csv`

After running iCatcher, but before using the browser tool, the user's directory might look like the below, where the corrections and raw annotation files are identical at creation. 

```
My project/ 
---other-project-files.xxx
---stimuli/
---whatever/
---scripts/
---analysis/
---data_description.json <- not expecting you to implement this, but as a note, the standard also provides a structured metadata file, following schema.org/Dataset
---data/
------my_video_folder/
---------arbitrarily-named-videofile.mp4
---------videoStream_{study-uuid}_{order-frame-name}_{response-uuid}_{timestamp}_{randomDigits}.mp4
---------videoStream_01a1b8-3e3e3e3e-4r4rr3_13-test-trials_4e4e4e4e-123ad50-9754b0_1683378560820_324.mp4
------icatcher/
---------label-corrections_video-arbitrarily-named-videofile_data.csv
---------label-corrections_study-{study-uuid}_frame-{order-frame-name}_response-{response-uuid}_timestamp-{timestamp}_hash-{randomDigits}_data.csv
---------label-corrections_study-01a1b8-3e3e3e3e-4r4rr3_frame-13-test-trials_response-4e4e4e4e-123ad50-9754b0_timestamp-1683378560820_hash-324_data.mp4
---------icatcher_raw/
------------label-raw_video-arbitrarily-named-videofile_data.csv
------------label-raw_study-{study-uuid}_frame-{order-frame-name}_response-{response-uuid}_timestamp-{timestamp}_hash-{randomDigits}_data.csv
------------label-raw_study-01a1b8-3e3e3e3e-4r4rr3_frame-13-test-trials_response-4e4e4e4e-123ad50-9754b0_timestamp-1683378560820_hash-324_data.mp4

```

**Comment by yoterel** [comment]
There is no capacity to do this for now, please reopen issue if you can assign a person to achieve this requirement.
