### ISSUE TITLE
Could you please add --flip_annotations for this version?

### ISSUE THREAD

**Issue by Elenaluchkina** [icatcherplus/icatcher_plus#62]
In the previous version, there was an option to flip annotations to be from the baby's perspective. Could you please add the same thing to the current version of iCatcher+? Thanks!!!

**Comment by yoterel** [comment]
Hi there, just to be sure I understand:
You essentially want the option for labels of the output to be flipped ? (i.e. left becomes right, and right becomes left, and away stays away) ?
Do you also want the output video to have those flipped labels? or just the annotation file?

Thanks

**Comment by yoterel** [comment]
A new command line option will be added in the next version called "--mirror_annotation".

**Comment by Elenaluchkina** [comment]
Awesome, thank you so much, this is amazing!!!

Elena
