### ISSUE TITLE
Make and add a logo?

### ISSUE THREAD

**Issue by shariliu** [icatcherplus/icatcher_plus#78]
Here are the few I've worked on - see what you think.

![iCatcher-logos_black](https://github.com/icatcherplus/icatcher_plus/assets/11280045/c92dfec3-d05a-42a7-8db2-872316bb984b)
![iCatcher-logos_transparent](https://github.com/icatcherplus/icatcher_plus/assets/11280045/0c4f6cab-4bce-48fd-ba3a-28a44b7b4d6b)
![iCatcher-logos_white](https://github.com/icatcherplus/icatcher_plus/assets/11280045/aca41948-cd91-44f8-993c-264bed464c92)
![iCatcher-logos](https://github.com/icatcherplus/icatcher_plus/assets/11280045/5b0fc42a-4e8c-4274-bd31-39cb034f49e7)

**Comment by yoterel** [comment]
Can you submit a pull request with the selected logo added to the website / repo ?
