### ISSUE TITLE
Issue downloading iCatcher

### ISSUE THREAD

**Issue by cgstone1** [icatcherplus/icatcher_plus#81]
In the process of downloading iCatcher+ on a Dell and received the below error:

Error loading "C:\Users\et121\AppData\Local\miniconda3\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

This computer is running Windows 10 and has the below conda--lists

Name                    Version                   Build  Channel
anaconda-anon-usage       0.4.4           py312hfc23b7f_100
aom                       3.9.1                he0c23c2_0    conda-forge
archspec                  0.2.3              pyhd3eb1b0_0
batch-face                1.5.0                    pypi_0    pypi
blinker                   1.8.2                    pypi_0    pypi
boltons                   23.0.0          py312haa95532_0
brotli-python             1.0.9           py312hd77b12b_8
bzip2                     1.0.8                h2bbff1b_6
ca-certificates           2024.7.4             h56e8100_0    conda-forge
cairo                     1.18.0               h32b962e_3    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py312h2bbff1b_1
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6           py312haa95532_0
conda                     24.7.1          py312h2e8e312_0    conda-forge
conda-content-trust       0.2.0           py312haa95532_1
conda-libmamba-solver     24.1.0             pyhd3eb1b0_0
conda-package-handling    2.3.0           py312haa95532_0
conda-package-streaming   0.10.0          py312haa95532_0
console_shortcut_miniconda 0.1.1                haa95532_2
contourpy                 1.2.1                    pypi_0    pypi
cryptography              42.0.5          py312h89fc84f_1
cycler                    0.12.1                   pypi_0    pypi
dav1d                     1.2.1                hcfcfb64_0    conda-forge
dill                      0.3.8                    pypi_0    pypi
distro                    1.9.0           py312haa95532_0
expat                     2.6.2                hd77b12b_0
ffmpeg                    7.0.1           gpl_h97ca3ef_105    conda-forge
ffmpeg-python             0.2.0                    pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
flask                     3.0.3                    pypi_0    pypi
flask-cors                4.0.1                    pypi_0    pypi
fmt                       9.1.0                h6d14046_1
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.1                   pypi_0    pypi
freetype                  2.12.1               hdaf720e_2    conda-forge
frozendict                2.4.2           py312haa95532_0
fsspec                    2024.6.1                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
graphite2                 1.3.13            h63175ca_1003    conda-forge
harfbuzz                  9.0.0                h2bedf89_1    conda-forge
icatcher                  0.2.3                    pypi_0    pypi
icu                       75.1                 he0c23c2_0    conda-forge
idna                      3.7             py312haa95532_0
itsdangerous              2.2.0                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jsonpatch                 1.33            py312haa95532_1
jsonpointer               2.1                pyhd3eb1b0_0
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.21.3               hdf4eb48_0    conda-forge
libarchive                3.6.2                h6f8411a_1    conda-forge
libcurl                   8.9.1                h18fefc2_0    conda-forge
libexpat                  2.6.2                h63175ca_0    conda-forge
libffi                    3.4.4                hd77b12b_1
libglib                   2.80.3               h7025463_1    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_2    conda-forge
libmamba                  1.5.8                h99b1521_2
libmambapy                1.5.8           py312h77c03ed_2
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libsolv                   0.7.30               hbb528cf_0    conda-forge
libsqlite                 3.46.0               h2466b09_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libxml2                   2.12.7               h0f24e4e_4    conda-forge
libzlib                   1.3.1                h2466b09_1    conda-forge
lz4-c                     1.9.4                h2bbff1b_1
lzo                       2.10              hcfcfb64_1001    conda-forge
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.1                    pypi_0    pypi
menuinst                  2.1.1           py312h5da7b33_0
mpmath                    1.3.0                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
networkx                  3.3                      pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
opencv-transforms         0.0.6                    pypi_0    pypi
openh264                  2.4.1                h63175ca_0    conda-forge
openssl                   3.3.1                h2466b09_2    conda-forge
packaging                 23.2            py312haa95532_0
pandas                    2.2.2                    pypi_0    pypi
pathos                    0.3.2                    pypi_0    pypi
pcre2                     10.44                h3d7b363_0    conda-forge
pillow                    10.4.0                   pypi_0    pypi
pip                       24.0            py312haa95532_0
pixman                    0.43.4               h63175ca_0    conda-forge
platformdirs              3.10.0          py312haa95532_0
pluggy                    1.0.0           py312haa95532_1
pooch                     1.8.2                    pypi_0    pypi
powershell_shortcut_miniconda 0.0.1                haa95532_2
pox                       0.3.4                    pypi_0    pypi
ppft                      1.7.6.8                  pypi_0    pypi
pybind11-abi              5                    hd3eb1b0_0
pycosat                   0.6.6           py312h2bbff1b_1
pycparser                 2.21               pyhd3eb1b0_0
pyparsing                 3.1.2                    pypi_0    pypi
pysocks                   1.7.1           py312haa95532_0
python                    3.12.4          h889d299_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.12                    4_cp312    conda-forge
pytz                      2024.1                   pypi_0    pypi
reproc                    14.2.4               hd77b12b_2
reproc-cpp                14.2.4               hd77b12b_2
requests                  2.32.2          py312haa95532_0
ruamel.yaml               0.17.21         py312h2bbff1b_0
scipy                     1.14.0                   pypi_0    pypi
setuptools                69.5.1          py312haa95532_0
six                       1.16.0                   pypi_0    pypi
sixdrepnet                0.1.6                    pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0
svt-av1                   2.1.2                he0c23c2_0    conda-forge
sympy                     1.13.1                   pypi_0    pypi
tk                        8.6.13               h5226925_1    conda-forge
torch                     2.4.0                    pypi_0    pypi
torchvision               0.19.0                   pypi_0    pypi
tqdm                      4.66.4          py312hfc267ef_0
truststore                0.8.0           py312haa95532_0
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   2.2.2           py312haa95532_0
vc                        14.2                 h2eaa2aa_1
vc14_runtime              14.40.33810         ha82c5b3_20    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_20    conda-forge
werkzeug                  3.0.3                    pypi_0    pypi
wheel                     0.43.0          py312haa95532_0
win_inet_pton             1.1.0           py312haa95532_0
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xz                        5.4.6                h8cc25b3_1
yaml-cpp                  0.8.0                hd77b12b_1
zlib                      1.3.1                h2466b09_1    conda-forge
zstandard                 0.22.0          py312h3469f8a_0
zstd                      1.5.5                h12be248_0    conda-forge

**Comment by yoterel** [comment]
Can you paste the exact command line you used to download iCatcher?

**Comment by cgstone1** [comment]
Hi Yotam,
Yes, I used `pip install icatcher` to install onto the computer. Once that was complete, I ran `conda install -c conda-forge ffmpeg`.
Thanks!
Caitlin

**Comment by yoterel** [comment]
As a sanity check, can you please create a completely new environment with conda, and perform installation (if you haven't done so before posting this issue)?

make sure to deactivate the current one if it was activated **before** following the steps bellow (`conda deactivate your_environment_name`)

that is:

`conda create -n my_new_env python=3.10`
`conda activate my_new_env`
`pip install icatcher`

Does this work?

**Comment by cgstone1** [comment]
This was the magic key! Thank you so so much!
